### ISSUE TITLE
Lightpad position on multiple displays

### ISSUE THREAD

**Issue by flamesquirrel** [UbuntuBudgie/budgie-lightpad-applet#1]
When using multiple displays on Ubuntu Budgie 21.10, the Lightpad Applet always and only displays on the left most display in the array. The expected behavior is that the applet open on the display set as the primary display. The main issue with this, other than it not appearing where expected, is when the primary display's resolution is greater than that of the left most display. The result is that some of the icons then appear off-screen, as does the search bar and navigation strip.

The ideal solution would be for the panel to appear on the primary display at the correct resolution while extending the 'veil' to any other displays in the array. It would also be nice if clicking anywhere on the 'veil' would close the applet - much like a modal window functions in a web browser.

**Comment by fossfreedom** [comment]
this should be raised on the upstream tracker - lightpad itself needs to handle where it displays not the applet which just invokes the app.

https://github.com/libredeb/lightpad

**Comment by flamesquirrel** [comment]
Thank you, I've added to an existing issue on the upstream.
